### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by rayout** [Hexadorsimal/crabflask#1]
https://github.com/Hexadorsimal/crabflask/blob/838992c31f41e2bf482bac0aa0eaee81c8c83af6/hosts

Hi! I think you need to remove this and change password!
You can use ansible vault for storing sercret variables.

**Comment by proggga** [comment]
Yea, you should change password, and install rkhunter after it, install firawall and change ssh port,
Please use your private ssh key, and use ansible-vault command for secure things like that

**Comment by Hexadorsimal** [comment]
Wow thanks guys.  Whoops!
